### ISSUE TITLE
Provide a tutorial/getting started instructions

### ISSUE THREAD

**Issue by krichter722** [java-diff-utils/java-diff-utils-jycr#6]
Please provide a tutorial/getting started instructions in English in the README or link it there. Remove the changelog because it's not interesting enough to be in the README and somehow covered by `git log` or move it to a separate file.

**Comment by koppor** [comment]
Please go to https://github.com/java-diff-utils/java-diff-utils/wiki. Maybe, we will create a markdown-based homepage. Please keep watching the maintained fork https://github.com/java-diff-utils/java-diff-utils.
